### ISSUE TITLE
Image upload issue via Perch blog using CKeditor

### ISSUE THREAD

**Issue by ISO1976** [cognetif/tinyimg#2]
Attempting to insert an inline image using CKEditor prompts a "server error" browser popup in Chrome. The app within dashboard reports that the image has successfully been submitted and compressed, but checking the directories shows that it has not saved to resources folder, or in fact anywhere within the site (have tried designating a specific bucket also within the blog template, but also without success).

**Comment by cognetif** [comment]
Sorry for not seeing you issue earlier.

can you please add some information about the perch version, operating system etc.

I have added a blog and updated the posts template to use the ckeditor and have had no issues as you have reported.

**Comment by cognetif** [comment]
closing - not able to replicate.
