### ISSUE TITLE
Original Image is optimized, when it should not be

### ISSUE THREAD

**Issue by jaygeorge** [cognetif/tinyimg#3]
Correct me if I'm wrong but I believe the app is optimising the original image file that's uploaded, _as well as_ the new images generated by Perch.

If this is the case, then I think the correct behaviour would be to leave the original image alone, and only optimise newly generated images—this is what the Perch Kraken app does.

The reason for this is that if the developer decides to generate new sizes in future, they want to spin these off the original uncompressed image.
If new images are created from a compressed image then the images are effectively compressed twice which would result in a worse quality image.

## Proposed Solution

- Only optimise/send to the TinyImg API images that are generated by Perch
- Do not send the original uploaded image to TinyImg

I guess you might be able to do some kind of check against the original file name uploaded? Not sure how the Perch API works.

**Comment by jaygeorge** [comment]
I’ve been thinking about this more.

I now think that this behaviour could actually be seen as a good thing on some levels because it solves the issue of Perch failing to compress images that are uploaded at the correct dimensions, as per the ticket I logged here: https://community.perchcms.com/forum/thread/469-perch-not-compressing-images-that-are-not-resized/?postID=2113#post2113

As long as the TinyImage settings are not lossy then resizing from a compressed image is probably acceptable and wouldn’t be noticed.

For me, all considered, the current behaviour of the app is favourable—but from a purist point of view other people may _not_ want the original image touched.

If you were to solve this ticket I guess it would be nice to have a checkbox option in the settings? Something like ‘compress original uploaded image’. I would then check this option as a user since it’s my preferred behaviour :)

**Comment by cognetif** [comment]
From my experience with the Tiny api, "recompressing" an image didn't hinder the quality of the image, if an image was compressed the first round from 1Mb to 300Kb, the second time it would remain 300Kb. 

right now the compression is on 2 events: assets.create_image and assets.upload_image.  Kraken uses only assets.create_image.  I remember adding the assets.upload_image to help reduce the server diskspace usage.  

What do you think about adding an option to turn the assets.upload_image event on or off so users can decide if they want the original compressed as well ?

**Comment by jaygeorge** [comment]
Yes, I think that's a good idea.

I understand that if you run an image through the Tiny API twice it will understand that it's already been compressed and will not do anything, BUT I'm not sure it will understand that an image has already been compressed if it's been newly resized by php.

I think the default should be to leave the original image _uncompressed_, as per the Kraken app behaviour which Drew authored.

I will probably throw caution to the wind and tick the option to compress the original image too, but I think there will be others that will consider that behaviour a bit destructive.

**Comment by cognetif** [comment]
Closing as it has been addressed in Release v1.2.0
